/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as OshiRouteImport } from './routes/oshi'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthResetRouteImport } from './routes/auth_.reset'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const OshiRoute = OshiRouteImport.update({
  id: '/oshi',
  path: '/oshi',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth_/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/oshi': typeof OshiRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/auth/reset': typeof AuthResetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/oshi': typeof OshiRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/auth/reset': typeof AuthResetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/oshi': typeof OshiRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/auth_/reset': typeof AuthResetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/auth'
    | '/history'
    | '/oshi'
    | '/savings'
    | '/settings'
    | '/auth/reset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/auth'
    | '/history'
    | '/oshi'
    | '/savings'
    | '/settings'
    | '/auth/reset'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/auth'
    | '/history'
    | '/oshi'
    | '/savings'
    | '/settings'
    | '/auth_/reset'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  OshiRoute: typeof OshiRoute
  SavingsRoute: typeof SavingsRoute
  SettingsRoute: typeof SettingsRoute
  AuthResetRoute: typeof AuthResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oshi': {
      id: '/oshi'
      path: '/oshi'
      fullPath: '/oshi'
      preLoaderRoute: typeof OshiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/reset': {
      id: '/auth_/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  OshiRoute: OshiRoute,
  SavingsRoute: SavingsRoute,
  SettingsRoute: SettingsRoute,
  AuthResetRoute: AuthResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
